from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer
from jose import JWTError, jwt
from app.core.security import SECRET_KEY, ALGORITHM

# This forces the user to provide a token generated by /admin/auth/login
admin_oauth2_scheme = OAuth2PasswordBearer(tokenUrl="admin/auth/login")

async def get_current_admin(token: str = Depends(admin_oauth2_scheme)):
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate admin credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        email: str = payload.get("sub")
        is_admin: bool = payload.get("root_admin")
        
        if email is None or not is_admin:
            raise credentials_exception
            
        return payload
    except JWTError:
        raise credentials_exception
